/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("dev.equo.p2deps") version "1.7.8"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    // Eclipse Maven
    //p2AsMaven {
        //url("https://download.eclipse.org/sirius/updates/releases/7.5.0/2025-09/")
    //}
    // Official Sirius 7.5.0 P2 update site
    //p2AsMaven {
        //url("https://download.eclipse.org/sirius/updates/releases/7.5.0/2025-09/")
    //}

    /*
    maven {
        url = uri("https://repo.eclipse.org/content/groups/releases/")
        metadataSources {
            mavenPom()
            artifact()
        }
    }
    */
    //maven {
        //url = uri("https://repo.eclipse.org/content/repositories/sirius-releases/")
    //}
    //maven {
        //url = uri("https://repo.eclipse.org/content/groups/releases/")
    //}
    /*
    maven {
        url = uri("https://repo.eclipse.org/content/repositories/sirius-maven2-snapshots/")
        
        metadataSources {
            mavenPom()
            artifact()
        }
    }
    */
    flatDir {
        dirs(rootProject.file("libs"))
    }
}

p2deps {
    into("implementation") {
        p2repo("https://download.eclipse.org/sirius/updates/releases/7.5.0/2025-09/")
        install("org.eclipse.sirius")
        install("org.eclipse.sirius.diagram")
        install("org.eclipse.sirius.diagram.formatdata")
    }
}

dependencies {
    // EMF standalone dependencies
    // Source: https://mvnrepository.com/artifact/org.eclipse.emf/org.eclipse.emf.ecore
    implementation("org.eclipse.emf:org.eclipse.emf.ecore:2.42.0")
    // Source: https://mvnrepository.com/artifact/org.eclipse.emf/org.eclipse.emf.ecore.xmi
    implementation("org.eclipse.emf:org.eclipse.emf.ecore.xmi:2.40.0")
    // Source: https://mvnrepository.com/artifact/org.eclipse.emf/org.eclipse.emf.common
    implementation("org.eclipse.emf:org.eclipse.emf.common:2.45.0") 

    // Eclipse Sirius .odesign
    //https://repo.eclipse.org/#browse/browse:sirius-maven2-snapshots:org%2Feclipse%2Fsirius%2Forg.eclipse.sirius%2F7.5.0-SNAPSHOT%2F7.5.0-20251114.144540-27
    //implementation("org.eclipse.sirius:org.eclipse.sirius:7.5.0-20251114.144540-27")
    //implementation("org.eclipse.sirius:org.eclipse.sirius:7.5.0-SNAPSHOT")
    //implementation("org.eclipse.sirius:org.eclipse.sirius.diagram:7.5.0-SNAPSHOT")
    //implementation("org.eclipse.sirius:org.eclipse.sirius.diagram.formatdata:7.5.0-SNAPSHOT")
    //implementation("org.eclipse.sirius:org.eclipse.sirius:7.5.0")
    //implementation("org.eclipse.sirius:org.eclipse.sirius.diagram:7.5.0")
    //implementation("org.eclipse.sirius:org.eclipse.sirius.diagram.formatdata:7.5.0")
    //implementation("sirius-deps:org.eclipse.sirius:7.5.0")
    //implementation("sirius-deps:org.eclipse.sirius.diagram:7.5.0")               
    //implementation("sirius-deps:org.eclipse.sirius.diagram.formatdata:7.5.0")
    
    // ANTLR runtime
    // Source: https://mvnrepository.com/artifact/org.antlr/antlr4-runtime
    implementation("org.antlr:antlr4-runtime:4.13.1")

    // Local jar of karpfen dsl tools in libs/
    //implementation(files(rootProject.file("libs/karpfen-dsl-tools.jar")))
    //implementation(files("libs/karpfen-dsl-tools.jar"))
    implementation("karpfen:karpfen-dsl-tools:1.0")
    implementation("org.json:json:20240303")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.0.0")

    
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.karpfen.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
        showStackTraces = true
    }
}

// Generate OSGi plugin metadata into META-INF/MANIFEST.MF inside the output JAR
tasks.jar {
    manifest {
        attributes(
            mapOf(
                "Manifest-Version" to "1.0",
                "Bundle-ManifestVersion" to "2",
                "Bundle-Name" to "Karpfen Visual Roundtrip Plugin",
                "Bundle-SymbolicName" to "org.karpfen.roundtrip.plugin;singleton:=true",
                "Bundle-Version" to "1.0.0.qualifier",
                "Require-Bundle" to "org.eclipse.emf.ecore, org.eclipse.emf.ecore.xmi, org.eclipse.sirius, org.eclipse.sirius.diagram, org.eclipse.elk.sdk",
                "Export-Package" to "org.karpfen.transformer"
            )
        )
    }
}

// Compiles karpfen jar if not existing
tasks.register<Exec>("setupKarpfenJar") {
    val scriptFile = rootProject.file("setup-karpfen.ps1")
    val targetJar = rootProject.file("libs/karpfen-dsl-tools.jar")

    onlyIf {
        !targetJar.exists()
    }

    // Set execution directory to the root project directory
    workingDir = rootProject.projectDir

    commandLine(
        "powershell",
        "-NoProfile",
        "-ExecutionPolicy", "Bypass",
        "-File", scriptFile.absolutePath
    )
}

tasks.named("compileJava") {
    dependsOn("setupKarpfenJar")
}