/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.6.1/userguide/building_java_projects.html in the Gradle documentation.
 */

import org.gradle.internal.os.OperatingSystem

fun getSwtPlatform(): String {
    val os = OperatingSystem.current()
    val arch = System.getProperty("os.arch")
    return when {
        os.isWindows -> "win32.win32.x86_64"
        os.isMacOsX -> if (arch == "aarch64") "cocoa.macosx.aarch64" else "cocoa.macosx.x86_64"
        os.isLinux -> if (arch == "aarch64") "gtk.linux.aarch64" else "gtk.linux.x86_64"
        else -> "win32.win32.x86_64"
    }
}

// Eclipse SWT POM (Maven) resolves OS but it conflicts with Gradle, and to resolve it in Gradle we compute it ${osgi.platform}
configurations.all {
    resolutionStrategy.eachDependency {
        if (requested.name.startsWith("org.eclipse.swt")) {
            useTarget("org.eclipse.platform:org.eclipse.swt.${getSwtPlatform()}:${requested.version}")
        }
    }
}

plugins {
    application
}

repositories {
    mavenCentral()
    flatDir {
        dirs(rootProject.file("libs"))
    }
}

// Read eclipseHome from gradle.properties or environment variable
val eclipseHomePath: String = project.findProperty("eclipseHome") as? String
    ?: System.getenv("ECLIPSE_HOME")
    ?: "D:/!Bachelor/Bachelor/eclipse-modeling-2026-06-R-win32-x86_64/eclipse"

val eclipseHomeDirectory = file(eclipseHomePath)
val eclipsePluginsDir = file("$eclipseHomePath/plugins")

// Modeling, EMF, Sirius, UI and Runtime bundle prefixes
val allowedPrefixes = listOf(
    "org.eclipse.sirius",
    "org.eclipse.emf",
    "org.eclipse.acceleo",
    "org.eclipse.gmf",
    "org.eclipse.gef",
    "org.eclipse.draw2d",
    "org.eclipse.osgi",
    "org.eclipse.equinox",
    "org.eclipse.core",
    "org.eclipse.ui",
    "org.eclipse.jface",
    "org.eclipse.swt",
    "org.eclipse.text",
    "com.google.guava",
    "com.ibm.icu"
)

// Selects only relevant modeling bundles and deduplicates (picks 7.6.0 over 7.5.0)
val eclipsePlugins: FileCollection = files(provider {
    if (!eclipsePluginsDir.exists()) return@provider emptyList<File>()

    val allJars = eclipsePluginsDir.listFiles { file ->
        file.isFile && file.name.endsWith(".jar") && !file.name.contains(".source_")
    } ?: emptyArray()

    allJars
        .filter { file -> allowedPrefixes.any { prefix -> file.name.startsWith(prefix) } }
        .groupBy { file ->
            // Extract bundle name before the version delimiter '_'
            if (file.name.contains('_')) file.name.substringBeforeLast('_') else file.nameWithoutExtension
        }
        .values
        .map { duplicateJars ->
            // Pick highest version string
            duplicateJars.maxByOrNull { it.name }!!
        }
})

dependencies {
    // Includes eclipse dependencies - runtime
    compileOnly(eclipsePlugins)

    // Third-party runtime dependencies bundled into the plugin FAT JAR
    implementation("org.antlr:antlr4-runtime:4.13.1")
    implementation("karpfen:karpfen-dsl-tools:1.0")
    implementation("org.json:json:20240303")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.0.0")

    // Test dependencies
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testImplementation(eclipsePlugins)
    testImplementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.karpfen.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    testLogging {
        events("passed", "skipped", "failed")
        showStandardStreams = true
        showStackTraces = true
    }
}

// Compiles karpfen jar if not existing
tasks.register<Exec>("setupKarpfenJar") {
    val scriptFile = rootProject.file("setup-karpfen.ps1")
    val targetJar = rootProject.file("libs/karpfen-dsl-tools.jar")

    onlyIf {
        !targetJar.exists()
    }

    // Set execution directory to the root project directory
    workingDir = rootProject.projectDir

    commandLine(
        "powershell",
        "-NoProfile",
        "-ExecutionPolicy", "Bypass",
        "-File", scriptFile.absolutePath
    )
}

tasks.named("compileJava") {
    dependsOn("setupKarpfenJar")
}

// Task for .odesign generation
val generateOdesignTask = tasks.register<JavaExec>("generateOdesign") {
    group = "build"
    description = "Generates karpfen.odesign directly into src/main/resources/description/"
    classpath = sourceSets["main"].runtimeClasspath + sourceSets["main"].compileClasspath
    mainClass.set("org.karpfen.design.OdesignGenerator")
    workingDir = projectDir
    dependsOn(tasks.named("compileJava"))
}

// Generate OSGi plugin metadata into META-INF/MANIFEST.MF inside the output JAR
val jarTask = tasks.named<Jar>("jar") {
    dependsOn(generateOdesignTask)
    archiveFileName.set("org.karpfen.roundtrip.plugin_1.0.0.jar")

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    // plugin.xml root
    from(project.file("plugin.xml"))
    from(rootProject.file("plugin.xml"))

    // odesign
    from(project.file("src/main/resources/description")) {
        into("description")
    }

    // templates
    from(project.file("src/main/resources/templates")) {
        into("templates")
    }

    // Bundle only runtime third-party dependencies (ANTLR, Kotlin, JSON, Karpfen Tools)
    from({
        configurations.runtimeClasspath.get().map { zipTree(it) }
    }) {
        exclude(
            "META-INF/*.SF",
            "META-INF/*.DSA",
            "META-INF/*.RSA",
            "META-INF/MANIFEST.MF",
            "META-INF/INDEX.LIST"
        )
    }

    // OSGi manifest definition
    manifest {
        attributes(
            mapOf(
                "Manifest-Version" to "1.0",
                "Bundle-ManifestVersion" to "2",
                "Bundle-Name" to "Karpfen Visual Roundtrip Plugin",
                "Bundle-SymbolicName" to "org.karpfen.roundtrip.plugin;singleton:=true",
                "Bundle-Version" to "1.0.0",
                "Bundle-RequiredExecutionEnvironment" to "JavaSE-21",
                "Bundle-Activator" to "org.karpfen.design.KarpfenPluginActivator",
                "Bundle-ActivationPolicy" to "lazy",
                "Require-Bundle" to listOf(
                    "org.eclipse.osgi",
                    "org.eclipse.core.runtime",
                    "org.eclipse.core.resources",
                    "org.eclipse.ui",
                    "org.eclipse.ui.workbench",
                    "org.eclipse.ui.workbench.texteditor",
                    "org.eclipse.ui.editors",
                    "org.eclipse.ui.ide",
                    "org.eclipse.jface.text",
                    "org.eclipse.emf.ecore",
                    "org.eclipse.emf.ecore.xmi",
                    "org.eclipse.emf.common",
                    "org.eclipse.emf.transaction",
                    "org.eclipse.emf.workspace",
                    "org.eclipse.sirius",
                    "org.eclipse.sirius.diagram",
                    "org.eclipse.sirius.diagram.ui",
                    "org.eclipse.sirius.ui",
                    "org.eclipse.sirius.common.acceleo.aql",
                    "org.eclipse.acceleo.query",
                    "org.eclipse.acceleo.aql"
                ).joinToString(","),
                "Export-Package" to "org.karpfen.transformer, org.karpfen.design, org.karpfen.resource, org.karpfen.serializer, org.karpfen.editor"
            )
        )
    }
}

// Capture providers and file handles at configuration time
val jarArchiveFile = jarTask.flatMap { it.archiveFile }

tasks.register("eclipsereload") {
    group = "application"
    description = "Packages JAR, cleans OSGi bundle cache inside Eclipse folder DEV"
    dependsOn(jarTask)

    val eclipseDir = eclipseHomeDirectory
    val jarFileProvider = jarArchiveFile

    doLast {
        val dropinsDir = File(eclipseDir, "dropins")
        val osgiCacheDir = File(eclipseDir, "configuration/org.eclipse.osgi")

        // Delete Eclipse OSGi runtime cache to force clean bundle resolution
        if (osgiCacheDir.exists()) {
            println("[eclipsereload] Removing OSGi cache: ${osgiCacheDir.absolutePath}")
            osgiCacheDir.deleteRecursively()
        }

        // Deploy fresh plugin FAT JAR to dropins/
        dropinsDir.mkdirs()
        val builtJar = jarFileProvider.get().asFile
        val targetDropin = File(dropinsDir, builtJar.name)

        println("[eclipsereload] Deploying plugin JAR -> ${targetDropin.absolutePath}")
        builtJar.copyTo(targetDropin, overwrite = true)
    }
}